/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateMachine,
    CreateMachineFromJSON,
    CreateMachineToJSON,
    GenericError,
    GenericErrorFromJSON,
    GenericErrorToJSON,
    Machine,
    MachineFromJSON,
    MachineToJSON,
} from '../models';

export interface CreateMachineRequest {
    createMachine: CreateMachine;
}

/**
 * MachinesApi - interface
 * 
 * @export
 * @interface MachinesApiInterface
 */
export interface MachinesApiInterface {
    /**
     * 
     * @summary creates a new machine
     * @param {CreateMachine} createMachine create a new machine
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MachinesApiInterface
     */
    createMachineRaw(requestParameters: CreateMachineRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Machine>>;

    /**
     * creates a new machine
     */
    createMachine(requestParameters: CreateMachineRequest, initOverrides?: RequestInit): Promise<Machine>;

    /**
     * 
     * @summary fetches machines
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MachinesApiInterface
     */
    fetchMachinesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Machine>>>;

    /**
     * fetches machines
     */
    fetchMachines(initOverrides?: RequestInit): Promise<Array<Machine>>;

}

/**
 * 
 */
export class MachinesApi extends runtime.BaseAPI implements MachinesApiInterface {

    /**
     * creates a new machine
     */
    async createMachineRaw(requestParameters: CreateMachineRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Machine>> {
        if (requestParameters.createMachine === null || requestParameters.createMachine === undefined) {
            throw new runtime.RequiredError('createMachine','Required parameter requestParameters.createMachine was null or undefined when calling createMachine.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("userAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/machines/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMachineToJSON(requestParameters.createMachine),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MachineFromJSON(jsonValue));
    }

    /**
     * creates a new machine
     */
    async createMachine(requestParameters: CreateMachineRequest, initOverrides?: RequestInit): Promise<Machine> {
        const response = await this.createMachineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * fetches machines
     */
    async fetchMachinesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Machine>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("userAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/machines/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MachineFromJSON));
    }

    /**
     * fetches machines
     */
    async fetchMachines(initOverrides?: RequestInit): Promise<Array<Machine>> {
        const response = await this.fetchMachinesRaw(initOverrides);
        return await response.value();
    }

}
