# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BaseTakeuchiTfmAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BaseTakeuchiTfmAdapter - a model defined in OpenAPI

        client_secret: The client_secret of this BaseTakeuchiTfmAdapter.
        client_id: The client_id of this BaseTakeuchiTfmAdapter.
        token_url: The token_url of this BaseTakeuchiTfmAdapter.
    """

    client_secret: str
    client_id: str
    token_url: str


BaseTakeuchiTfmAdapter.update_forward_refs()
