# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BaseAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BaseAdapter - a model defined in OpenAPI

        id: The id of this BaseAdapter.
        user_id: The user_id of this BaseAdapter.
        created_at: The created_at of this BaseAdapter.
        updated_at: The updated_at of this BaseAdapter.
        adapter_name: The adapter_name of this BaseAdapter.
        cron_expression: The cron_expression of this BaseAdapter.
        data_url: The data_url of this BaseAdapter.
    """

    id: int
    user_id: int
    created_at: datetime
    updated_at: datetime
    adapter_name: str
    cron_expression: str
    data_url: str


BaseAdapter.update_forward_refs()
