# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BaseWackerNeusonKramerAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BaseWackerNeusonKramerAdapter - a model defined in OpenAPI

        token_url: The token_url of this BaseWackerNeusonKramerAdapter.
        username: The username of this BaseWackerNeusonKramerAdapter.
        password: The password of this BaseWackerNeusonKramerAdapter.
        client_id: The client_id of this BaseWackerNeusonKramerAdapter.
        client_secret: The client_secret of this BaseWackerNeusonKramerAdapter.
    """

    token_url: str
    username: str
    password: str
    client_id: str
    client_secret: str


BaseWackerNeusonKramerAdapter.update_forward_refs()
