# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BaseVolvoCaretrackAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BaseVolvoCaretrackAdapter - a model defined in OpenAPI

        username: The username of this BaseVolvoCaretrackAdapter.
        password: The password of this BaseVolvoCaretrackAdapter.
    """

    username: str
    password: str


BaseVolvoCaretrackAdapter.update_forward_refs()
