# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BaseCreateAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BaseCreateAdapter - a model defined in OpenAPI

        adapter_name: The adapter_name of this BaseCreateAdapter.
        data_url: The data_url of this BaseCreateAdapter.
        cron_expression: The cron_expression of this BaseCreateAdapter.
    """

    adapter_name: str
    data_url: str
    cron_expression: str


BaseCreateAdapter.update_forward_refs()
