# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from app.api.models.adapter_enums import AdapterEnums
from app.api.models.base_adapter import BaseAdapter
from app.api.models.bearer_token import BearerToken
from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BearerTokenAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BearerTokenAdapter - a model defined in OpenAPI

        id: The id of this BearerTokenAdapter.
        user_id: The user_id of this BearerTokenAdapter.
        created_at: The created_at of this BearerTokenAdapter.
        updated_at: The updated_at of this BearerTokenAdapter.
        adapter_name: The adapter_name of this BearerTokenAdapter.
        cron_expression: The cron_expression of this BearerTokenAdapter.
        authorization_type: The authorization_type of this BearerTokenAdapter.
        bearer_token: The bearer_token of this BearerTokenAdapter.
    """

    id: int
    user_id: int
    created_at: datetime
    updated_at: datetime
    adapter_name: AdapterEnums
    cron_expression: str
    authorization_type: str
    bearer_token: str


BearerTokenAdapter.update_forward_refs()
