# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from app.api.models.base_create_adapter import BaseCreateAdapter
from app.api.models.base_takeuchi_tfm_adapter import BaseTakeuchiTfmAdapter
from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class CreateTakeuchiTfmAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateTakeuchiTfmAdapter - a model defined in OpenAPI

        adapter_name: The adapter_name of this CreateTakeuchiTfmAdapter.
        data_url: The data_url of this CreateTakeuchiTfmAdapter.
        cron_expression: The cron_expression of this CreateTakeuchiTfmAdapter.
        client_secret: The client_secret of this CreateTakeuchiTfmAdapter.
        client_id: The client_id of this CreateTakeuchiTfmAdapter.
        token_url: The token_url of this CreateTakeuchiTfmAdapter.
    """

    adapter_name: str
    data_url: str
    cron_expression: str
    client_secret: str
    client_id: str
    token_url: str


CreateTakeuchiTfmAdapter.update_forward_refs()
