# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from app.api.models.base_create_adapter import BaseCreateAdapter
from app.api.models.base_volvo_caretrack_adapter import BaseVolvoCaretrackAdapter
from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class CreateVolvoCaretrackAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateVolvoCaretrackAdapter - a model defined in OpenAPI

        adapter_name: The adapter_name of this CreateVolvoCaretrackAdapter.
        data_url: The data_url of this CreateVolvoCaretrackAdapter.
        cron_expression: The cron_expression of this CreateVolvoCaretrackAdapter.
        username: The username of this CreateVolvoCaretrackAdapter.
        password: The password of this CreateVolvoCaretrackAdapter.
    """

    adapter_name: str
    data_url: str
    cron_expression: str
    username: str
    password: str


CreateVolvoCaretrackAdapter.update_forward_refs()
