# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Credentials(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Credentials - a model defined in OpenAPI

        username: The username of this Credentials [Optional].
        password: The password of this Credentials.
        scope: The scope of this Credentials [Optional].
        client_id: The client_id of this Credentials [Optional].
        client_secret: The client_secret of this Credentials [Optional].
    """

    username: Optional[str] = None
    password: str
    scope: Optional[str] = None
    client_id: Optional[str] = None
    client_secret: Optional[str] = None

Credentials.update_forward_refs()
