# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from app.api.models.token import Token
from app.api.models.user import User
from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class LoginResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LoginResponse - a model defined in OpenAPI

        user: The user of this LoginResponse.
        refresh_token: The refresh_token of this LoginResponse.
        access_token: The access_token of this LoginResponse.
    """

    user: User
    refresh_token: str
    access_token: str


LoginResponse.update_forward_refs()
