# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Machine(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Machine - a model defined in OpenAPI

        id: The id of this Machine [Optional].
        created_at: The created_at of this Machine [Optional].
        updated_at: The updated_at of this Machine [Optional].
        unit_installed_at: The unit_installed_at of this Machine [Optional].
        oem_name: The oem_name of this Machine [Optional].
        model: The model of this Machine [Optional].
        make: The make of this Machine [Optional].
        equipment_id: The equipment_id of this Machine [Optional].
        serial_number: The serial_number of this Machine [Optional].
        pin: The pin of this Machine [Optional].
    """

    id: Optional[int] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    unit_installed_at: Optional[datetime] = None
    oem_name: Optional[str] = None
    model: Optional[str] = None
    make: Optional[str] = None
    equipment_id: Optional[str] = None
    serial_number: Optional[str] = None
    pin: Optional[str] = None


Machine.update_forward_refs()
