# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from app.api.models.base_adapter import BaseAdapter
from app.api.models.base_takeuchi_tfm_adapter import BaseTakeuchiTfmAdapter
from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class TakeuchiTfmAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TakeuchiTfmAdapter - a model defined in OpenAPI

        id: The id of this TakeuchiTfmAdapter.
        user_id: The user_id of this TakeuchiTfmAdapter.
        created_at: The created_at of this TakeuchiTfmAdapter.
        updated_at: The updated_at of this TakeuchiTfmAdapter.
        adapter_name: The adapter_name of this TakeuchiTfmAdapter.
        cron_expression: The cron_expression of this TakeuchiTfmAdapter.
        data_url: The data_url of this TakeuchiTfmAdapter.
        client_secret: The client_secret of this TakeuchiTfmAdapter.
        client_id: The client_id of this TakeuchiTfmAdapter.
        token_url: The token_url of this TakeuchiTfmAdapter.
    """

    id: int
    user_id: int
    created_at: datetime
    updated_at: datetime
    adapter_name: str
    cron_expression: str
    data_url: str
    client_secret: str
    client_id: str
    token_url: str


TakeuchiTfmAdapter.update_forward_refs()
