# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class UpdateUser(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UpdateUser - a model defined in OpenAPI

        is_superuser: The is_superuser of this UpdateUser [Optional].
        first_name: The first_name of this UpdateUser [Optional].
        last_name: The last_name of this UpdateUser [Optional].
        email: The email of this UpdateUser [Optional].
        password: The password of this UpdateUser [Optional].
    """

    is_superuser: Optional[bool] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: Optional[str] = None
    password: Optional[str] = None

UpdateUser.update_forward_refs()
