# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class VolvoCaretrackAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VolvoCaretrackAdapter - a model defined in OpenAPI

        id: The id of this VolvoCaretrackAdapter.
        user_id: The user_id of this VolvoCaretrackAdapter.
        created_at: The created_at of this VolvoCaretrackAdapter.
        updated_at: The updated_at of this VolvoCaretrackAdapter.
        adapter_name: The adapter_name of this VolvoCaretrackAdapter.
        cron_expression: The cron_expression of this VolvoCaretrackAdapter.
        data_url: The data_url of this VolvoCaretrackAdapter.
        username: The username of this VolvoCaretrackAdapter.
        password: The password of this VolvoCaretrackAdapter.
    """

    id: int
    user_id: int
    created_at: datetime
    updated_at: datetime
    adapter_name: str
    cron_expression: str
    data_url: str
    username: str
    password: str


VolvoCaretrackAdapter.update_forward_refs()
