# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class WackerNeusonKramerAdapter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    WackerNeusonKramerAdapter - a model defined in OpenAPI

        id: The id of this WackerNeusonKramerAdapter.
        user_id: The user_id of this WackerNeusonKramerAdapter.
        created_at: The created_at of this WackerNeusonKramerAdapter.
        updated_at: The updated_at of this WackerNeusonKramerAdapter.
        adapter_name: The adapter_name of this WackerNeusonKramerAdapter.
        cron_expression: The cron_expression of this WackerNeusonKramerAdapter.
        data_url: The data_url of this WackerNeusonKramerAdapter.
        token_url: The token_url of this WackerNeusonKramerAdapter.
        username: The username of this WackerNeusonKramerAdapter.
        password: The password of this WackerNeusonKramerAdapter.
        client_id: The client_id of this WackerNeusonKramerAdapter.
        client_secret: The client_secret of this WackerNeusonKramerAdapter.
    """

    id: int
    user_id: int
    created_at: datetime
    updated_at: datetime
    adapter_name: str
    cron_expression: str
    data_url: str
    token_url: str
    username: str
    password: str
    client_id: str
    client_secret: str


WackerNeusonKramerAdapter.update_forward_refs()
