repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--config, fastapi-master-api/pyproject.toml]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-docstrings]
        args:
          [--config, fastapi-master-api/.flake8, --count, --statistics, --exit-zero]

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args:
          [--settings-path, fastapi-master-api/pyproject.toml]

  # Frontend - JS/TS
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        files: frontend/public/.*\.json
        types: [file]
        additional_dependencies:
          - prettier-plugin-sort-json@0.0.2

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.0-beta.2
    hooks:
      - id: eslint
        files: frontend/.*\.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@4.28.5"
          - "@typescript-eslint/parser@4.28.5"
          - "@trivago/prettier-plugin-sort-imports@2.0.2"
          - eslint-import-resolver-typescript@2.4.0
          - eslint-plugin-import@2.23.4
          - eslint-config-prettier@8.3.0
          - eslint-config-react-app@6.0.0
          - eslint-plugin-cypress@2.11.3
          - eslint-config-prettier@8.3.0
          - eslint-plugin-import@2.23.2
          - eslint-plugin-jsx-a11y@6.4.1
          - eslint-plugin-prettier@3.4.0
          - eslint-plugin-react@7.23.2
          - eslint-plugin-react-hooks@4.2.0
          - typescript@4.3.5
        # some rules need to be deactivated as they need the node_modules folder
        # or TS env to work
        args:
          [
            "--rule=import/default: off",
            "--rule=import/no-cycle: off",
            --max-warnings=0,
            --fix,
          ]

  # API - OpenAPI
  - repo: https://github.com/APIDevTools/swagger-cli
    rev: v4.0.4
    hooks:
      - id: swagger-validation
        name: swagger-validation:src
        args: [validate, openapi-spec/src/openapi-spec.yaml]
      - id: swagger-validation
        name: swagger-validation:build
        args: [validate, openapi-spec/build/openapi.yaml]
#
#  - repo: local
#    hooks:
#      - id: custom-script-file
#        name: custom-script-file
#        entry: fastapi-master-api/generate_reports.sh
#        language: script
#        types: [python]
#        pass_filenames: false
