"""create adapter table

Revision ID: 32785f9a2f10
Revises: d62c9da09bb2
Create Date: 2022-01-02 14:37:40.324059

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "32785f9a2f10"
down_revision = "d62c9da09bb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adapters",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("cron_expression", sa.Text(), nullable=True),
        sa.Column("adapter_name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], initially="DEFERRED", deferrable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_adapters_user_id"), "adapters", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adapters_user_id"), table_name="adapters")
    op.drop_table("adapters")
    # ### end Alembic commands ###
