"""added a machines table for aemp

Revision ID: 46b0600f9da9
Revises: 823a2ed817ac
Create Date: 2022-03-19 19:01:10.848102

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46b0600f9da9"
down_revision = "823a2ed817ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metrics",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("machine_id", sa.Integer(), nullable=True),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["machine_id"], ["machines.id"], initially="DEFERRED", deferrable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], initially="DEFERRED", deferrable=True
        ),
        sa.PrimaryKeyConstraint("event_at", "machine_id", "metric"),
    )
    op.create_index(op.f("ix_metrics_user_id"), "metrics", ["user_id"], unique=False)
    op.alter_column(
        "machines", "serial_number", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("machines", "serial_number", existing_type=sa.TEXT(), nullable=True)
    op.drop_index(op.f("ix_metrics_user_id"), table_name="metrics")
    op.drop_table("metrics")
    # ### end Alembic commands ###
