"""updated adapter tables to AEMP

Revision ID: c9f78a7d00ab
Revises: 676c84bcd7f8
Create Date: 2022-01-31 21:51:40.759478

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c9f78a7d00ab"
down_revision = "676c84bcd7f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adapter_volvo_caretrack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["adapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "adapter_wacker_neuson_kramer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_url", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("client_secret", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["adapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("authorization_bearer_token")
    op.add_column("adapters", sa.Column("data_url", sa.Text(), nullable=False))
    op.drop_column("adapters", "authorization_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "adapters",
        sa.Column("authorization_type", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("adapters", "data_url")
    op.create_table(
        "authorization_bearer_token",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("bearer_token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["adapters.id"],
            name="authorization_bearer_token_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="authorization_bearer_token_pkey"),
    )
    op.drop_table("adapter_wacker_neuson_kramer")
    op.drop_table("adapter_volvo_caretrack")
    # ### end Alembic commands ###
