"""make serial number a primary key

Revision ID: cd3fd309b90a
Revises: dbc29584ac4a
Create Date: 2022-03-19 13:47:31.369796

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd3fd309b90a"
down_revision = "dbc29584ac4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "machines", "serial_number", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column("machines", "pin", existing_type=sa.TEXT(), nullable=False)
    op.drop_constraint("machines_pin_key", "machines", type_="unique")
    op.drop_constraint("machines_serial_number_key", "machines", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "machines_serial_number_key", "machines", ["serial_number"]
    )
    op.create_unique_constraint("machines_pin_key", "machines", ["pin"])
    op.alter_column("machines", "pin", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("machines", "serial_number", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
