"""make serial and pin unique

Revision ID: dbc29584ac4a
Revises: 823a2ed817ac
Create Date: 2022-03-19 12:21:51.056858

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dbc29584ac4a"
down_revision = "823a2ed817ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "machines", ["serial_number"])
    op.create_unique_constraint(None, "machines", ["pin"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "machines", type_="unique")
    op.drop_constraint(None, "machines", type_="unique")
    # ### end Alembic commands ###
