"""added a machines table for aemp

Revision ID: f92312a125f9
Revises: a1bb1cb45c0a
Create Date: 2022-03-15 22:31:25.550559

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f92312a125f9"
down_revision = "a1bb1cb45c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
