"""unique constraint on adapter and user

Revision ID: fbc29a24c086
Revises: 32785f9a2f10
Create Date: 2022-01-02 15:19:54.712642

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fbc29a24c086"
down_revision = "32785f9a2f10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_adapter", "adapters", ["user_id", "adapter_name"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_adapter", "adapters", type_="unique")
    # ### end Alembic commands ###
