"""add _at to last login

Revision ID: fbc4b09fc544
Revises: 12cf361c4c31
Create Date: 2021-12-23 12:50:44.888105

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fbc4b09fc544"
down_revision = "12cf361c4c31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_login", nullable=False, new_column_name="last_login_at"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_login_at", nullable=False, new_column_name="last_login"
    )
    # ### end Alembic commands ###
