/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LiebherrLidatAdapter,
    TakeuchiTfmAdapter,
    VolvoCaretrackAdapter,
    WackerNeusonKramerAdapter,
    LiebherrLidatAdapterFromJSONTyped,
    LiebherrLidatAdapterToJSON,
    TakeuchiTfmAdapterFromJSONTyped,
    TakeuchiTfmAdapterToJSON,
    VolvoCaretrackAdapterFromJSONTyped,
    VolvoCaretrackAdapterToJSON,
    WackerNeusonKramerAdapterFromJSONTyped,
    WackerNeusonKramerAdapterToJSON,
} from './';

/**
 * @type Adapter
 * 
 * @export
 */
export type Adapter = ;

export function AdapterFromJSON(json: any): Adapter {
    return AdapterFromJSONTyped(json, false);
}

export function AdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Adapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['adapterName']) {
        default:
            throw new Error(`No variant of Adapter exists with 'adapterName=${json['adapterName']}'`);
    }
}

export function AdapterToJSON(value?: Adapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['adapterName']) {
        default:
            throw new Error(`No variant of Adapter exists with 'adapterName=${value['adapterName']}'`);
    }
}

