/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseTakeuchiTfmAdapter
 */
export interface BaseTakeuchiTfmAdapter {
    /**
     * 
     * @type {string}
     * @memberof BaseTakeuchiTfmAdapter
     */
    clientSecret: string;
    /**
     * 
     * @type {string}
     * @memberof BaseTakeuchiTfmAdapter
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof BaseTakeuchiTfmAdapter
     */
    tokenUrl: string;
}

export function BaseTakeuchiTfmAdapterFromJSON(json: any): BaseTakeuchiTfmAdapter {
    return BaseTakeuchiTfmAdapterFromJSONTyped(json, false);
}

export function BaseTakeuchiTfmAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseTakeuchiTfmAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientSecret': json['client_secret'],
        'clientId': json['client_id'],
        'tokenUrl': json['token_url'],
    };
}

export function BaseTakeuchiTfmAdapterToJSON(value?: BaseTakeuchiTfmAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client_secret': value.clientSecret,
        'client_id': value.clientId,
        'token_url': value.tokenUrl,
    };
}
