/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseAdapter
 */
export interface BaseAdapter {
    /**
     * 
     * @type {number}
     * @memberof BaseAdapter
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof BaseAdapter
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof BaseAdapter
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof BaseAdapter
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof BaseAdapter
     */
    adapterName: string;
    /**
     * 
     * @type {string}
     * @memberof BaseAdapter
     */
    cronExpression: string;
    /**
     * 
     * @type {string}
     * @memberof BaseAdapter
     */
    dataUrl: string;
}

export function BaseAdapterFromJSON(json: any): BaseAdapter {
    return BaseAdapterFromJSONTyped(json, false);
}

export function BaseAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'adapterName': json['adapter_name'],
        'cronExpression': json['cron_expression'],
        'dataUrl': json['data_url'],
    };
}

export function BaseAdapterToJSON(value?: BaseAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'user_id': value.userId,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'adapter_name': value.adapterName,
        'cron_expression': value.cronExpression,
        'data_url': value.dataUrl,
    };
}
