/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseLiebherrLidatAdapter
 */
export interface BaseLiebherrLidatAdapter {
    /**
     * 
     * @type {string}
     * @memberof BaseLiebherrLidatAdapter
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof BaseLiebherrLidatAdapter
     */
    password: string;
}

export function BaseLiebherrLidatAdapterFromJSON(json: any): BaseLiebherrLidatAdapter {
    return BaseLiebherrLidatAdapterFromJSONTyped(json, false);
}

export function BaseLiebherrLidatAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseLiebherrLidatAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function BaseLiebherrLidatAdapterToJSON(value?: BaseLiebherrLidatAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}
