/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseWackerNeusonKramerAdapter
 */
export interface BaseWackerNeusonKramerAdapter {
    /**
     * 
     * @type {string}
     * @memberof BaseWackerNeusonKramerAdapter
     */
    tokenUrl: string;
    /**
     * 
     * @type {string}
     * @memberof BaseWackerNeusonKramerAdapter
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof BaseWackerNeusonKramerAdapter
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof BaseWackerNeusonKramerAdapter
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof BaseWackerNeusonKramerAdapter
     */
    clientSecret: string;
}

export function BaseWackerNeusonKramerAdapterFromJSON(json: any): BaseWackerNeusonKramerAdapter {
    return BaseWackerNeusonKramerAdapterFromJSONTyped(json, false);
}

export function BaseWackerNeusonKramerAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseWackerNeusonKramerAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenUrl': json['token_url'],
        'username': json['username'],
        'password': json['password'],
        'clientId': json['client_id'],
        'clientSecret': json['client_secret'],
    };
}

export function BaseWackerNeusonKramerAdapterToJSON(value?: BaseWackerNeusonKramerAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token_url': value.tokenUrl,
        'username': value.username,
        'password': value.password,
        'client_id': value.clientId,
        'client_secret': value.clientSecret,
    };
}
