/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseCreateAdapter
 */
export interface BaseCreateAdapter {
    /**
     * 
     * @type {string}
     * @memberof BaseCreateAdapter
     */
    adapterName: string;
    /**
     * 
     * @type {string}
     * @memberof BaseCreateAdapter
     */
    dataUrl: string;
    /**
     * 
     * @type {string}
     * @memberof BaseCreateAdapter
     */
    cronExpression: string;
}

export function BaseCreateAdapterFromJSON(json: any): BaseCreateAdapter {
    return BaseCreateAdapterFromJSONTyped(json, false);
}

export function BaseCreateAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseCreateAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'adapterName': json['adapter_name'],
        'dataUrl': json['data_url'],
        'cronExpression': json['cron_expression'],
    };
}

export function BaseCreateAdapterToJSON(value?: BaseCreateAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'adapter_name': value.adapterName,
        'data_url': value.dataUrl,
        'cron_expression': value.cronExpression,
    };
}
