/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CreateLiebherrLidatAdapter,
    CreateTakeuchiTfmAdapter,
    CreateVolvoCaretrackAdapter,
    CreateWackerNeusonKramerAdapter,
    CreateLiebherrLidatAdapterFromJSONTyped,
    CreateLiebherrLidatAdapterToJSON,
    CreateTakeuchiTfmAdapterFromJSONTyped,
    CreateTakeuchiTfmAdapterToJSON,
    CreateVolvoCaretrackAdapterFromJSONTyped,
    CreateVolvoCaretrackAdapterToJSON,
    CreateWackerNeusonKramerAdapterFromJSONTyped,
    CreateWackerNeusonKramerAdapterToJSON,
} from './';

/**
 * @type CreateAdapter
 * 
 * @export
 */
export type CreateAdapter = ;

export function CreateAdapterFromJSON(json: any): CreateAdapter {
    return CreateAdapterFromJSONTyped(json, false);
}

export function CreateAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['adapterName']) {
        default:
            throw new Error(`No variant of CreateAdapter exists with 'adapterName=${json['adapterName']}'`);
    }
}

export function CreateAdapterToJSON(value?: CreateAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['adapterName']) {
        default:
            throw new Error(`No variant of CreateAdapter exists with 'adapterName=${value['adapterName']}'`);
    }
}

