/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMachine
 */
export interface CreateMachine {
    /**
     * 
     * @type {number}
     * @memberof CreateMachine
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateMachine
     */
    unitInstalledAt?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMachine
     */
    oemName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMachine
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMachine
     */
    make?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMachine
     */
    equipmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMachine
     */
    serialNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMachine
     */
    pin?: string;
}

export function CreateMachineFromJSON(json: any): CreateMachine {
    return CreateMachineFromJSONTyped(json, false);
}

export function CreateMachineFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMachine {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'unitInstalledAt': !exists(json, 'unit_installed_at') ? undefined : json['unit_installed_at'],
        'oemName': json['oem_name'],
        'model': json['model'],
        'make': !exists(json, 'make') ? undefined : json['make'],
        'equipmentId': !exists(json, 'equipment_id') ? undefined : json['equipment_id'],
        'serialNumber': !exists(json, 'serial_number') ? undefined : json['serial_number'],
        'pin': !exists(json, 'pin') ? undefined : json['pin'],
    };
}

export function CreateMachineToJSON(value?: CreateMachine | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
        'unit_installed_at': value.unitInstalledAt,
        'oem_name': value.oemName,
        'model': value.model,
        'make': value.make,
        'equipment_id': value.equipmentId,
        'serial_number': value.serialNumber,
        'pin': value.pin,
    };
}
