/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseCreateAdapter,
    BaseCreateAdapterFromJSON,
    BaseCreateAdapterFromJSONTyped,
    BaseCreateAdapterToJSON,
    BaseVolvoCaretrackAdapter,
    BaseVolvoCaretrackAdapterFromJSON,
    BaseVolvoCaretrackAdapterFromJSONTyped,
    BaseVolvoCaretrackAdapterToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateVolvoCaretrackAdapter
 */
export interface CreateVolvoCaretrackAdapter {
    /**
     * 
     * @type {string}
     * @memberof CreateVolvoCaretrackAdapter
     */
    adapterName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVolvoCaretrackAdapter
     */
    dataUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVolvoCaretrackAdapter
     */
    cronExpression: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVolvoCaretrackAdapter
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVolvoCaretrackAdapter
     */
    password: string;
}

export function CreateVolvoCaretrackAdapterFromJSON(json: any): CreateVolvoCaretrackAdapter {
    return CreateVolvoCaretrackAdapterFromJSONTyped(json, false);
}

export function CreateVolvoCaretrackAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVolvoCaretrackAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'adapterName': json['adapter_name'],
        'dataUrl': json['data_url'],
        'cronExpression': json['cron_expression'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function CreateVolvoCaretrackAdapterToJSON(value?: CreateVolvoCaretrackAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'adapter_name': value.adapterName,
        'data_url': value.dataUrl,
        'cron_expression': value.cronExpression,
        'username': value.username,
        'password': value.password,
    };
}
