/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseCreateAdapter,
    BaseCreateAdapterFromJSON,
    BaseCreateAdapterFromJSONTyped,
    BaseCreateAdapterToJSON,
    BaseTakeuchiTfmAdapter,
    BaseTakeuchiTfmAdapterFromJSON,
    BaseTakeuchiTfmAdapterFromJSONTyped,
    BaseTakeuchiTfmAdapterToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateTakeuchiTfmAdapter
 */
export interface CreateTakeuchiTfmAdapter {
    /**
     * 
     * @type {string}
     * @memberof CreateTakeuchiTfmAdapter
     */
    adapterName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTakeuchiTfmAdapter
     */
    dataUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTakeuchiTfmAdapter
     */
    cronExpression: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTakeuchiTfmAdapter
     */
    clientSecret: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTakeuchiTfmAdapter
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTakeuchiTfmAdapter
     */
    tokenUrl: string;
}

export function CreateTakeuchiTfmAdapterFromJSON(json: any): CreateTakeuchiTfmAdapter {
    return CreateTakeuchiTfmAdapterFromJSONTyped(json, false);
}

export function CreateTakeuchiTfmAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTakeuchiTfmAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'adapterName': json['adapter_name'],
        'dataUrl': json['data_url'],
        'cronExpression': json['cron_expression'],
        'clientSecret': json['client_secret'],
        'clientId': json['client_id'],
        'tokenUrl': json['token_url'],
    };
}

export function CreateTakeuchiTfmAdapterToJSON(value?: CreateTakeuchiTfmAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'adapter_name': value.adapterName,
        'data_url': value.dataUrl,
        'cron_expression': value.cronExpression,
        'client_secret': value.clientSecret,
        'client_id': value.clientId,
        'token_url': value.tokenUrl,
    };
}
