/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateMetric,
    CreateMetricFromJSON,
    CreateMetricFromJSONTyped,
    CreateMetricToJSON,
    CreatedMetricBase,
    CreatedMetricBaseFromJSON,
    CreatedMetricBaseFromJSONTyped,
    CreatedMetricBaseToJSON,
} from './';

/**
 * 
 * @export
 * @interface Metric
 */
export interface Metric {
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    processedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    eventAt?: string;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    machineId: number;
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    metric?: string;
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    unit?: string;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    createdAt: string;
}

export function MetricFromJSON(json: any): Metric {
    return MetricFromJSONTyped(json, false);
}

export function MetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): Metric {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'processedAt': !exists(json, 'processed_at') ? undefined : json['processed_at'],
        'eventAt': !exists(json, 'event_at') ? undefined : json['event_at'],
        'machineId': json['machine_id'],
        'metric': !exists(json, 'metric') ? undefined : json['metric'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'userId': json['user_id'],
        'createdAt': json['created_at'],
    };
}

export function MetricToJSON(value?: Metric | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'processed_at': value.processedAt,
        'event_at': value.eventAt,
        'machine_id': value.machineId,
        'metric': value.metric,
        'value': value.value,
        'unit': value.unit,
        'user_id': value.userId,
        'created_at': value.createdAt,
    };
}
