/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseAdapter,
    BaseAdapterFromJSON,
    BaseAdapterFromJSONTyped,
    BaseAdapterToJSON,
    BaseVolvoCaretrackAdapter,
    BaseVolvoCaretrackAdapterFromJSON,
    BaseVolvoCaretrackAdapterFromJSONTyped,
    BaseVolvoCaretrackAdapterToJSON,
} from './';

/**
 * 
 * @export
 * @interface VolvoCaretrackAdapter
 */
export interface VolvoCaretrackAdapter {
    /**
     * 
     * @type {number}
     * @memberof VolvoCaretrackAdapter
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof VolvoCaretrackAdapter
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof VolvoCaretrackAdapter
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof VolvoCaretrackAdapter
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof VolvoCaretrackAdapter
     */
    adapterName: string;
    /**
     * 
     * @type {string}
     * @memberof VolvoCaretrackAdapter
     */
    cronExpression: string;
    /**
     * 
     * @type {string}
     * @memberof VolvoCaretrackAdapter
     */
    dataUrl: string;
    /**
     * 
     * @type {string}
     * @memberof VolvoCaretrackAdapter
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof VolvoCaretrackAdapter
     */
    password: string;
}

export function VolvoCaretrackAdapterFromJSON(json: any): VolvoCaretrackAdapter {
    return VolvoCaretrackAdapterFromJSONTyped(json, false);
}

export function VolvoCaretrackAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolvoCaretrackAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'adapterName': json['adapter_name'],
        'cronExpression': json['cron_expression'],
        'dataUrl': json['data_url'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function VolvoCaretrackAdapterToJSON(value?: VolvoCaretrackAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'user_id': value.userId,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'adapter_name': value.adapterName,
        'cron_expression': value.cronExpression,
        'data_url': value.dataUrl,
        'username': value.username,
        'password': value.password,
    };
}
