/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack Portfolio API
 * FastAPI of Fullstack Portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseAdapter,
    BaseAdapterFromJSON,
    BaseAdapterFromJSONTyped,
    BaseAdapterToJSON,
    BaseWackerNeusonKramerAdapter,
    BaseWackerNeusonKramerAdapterFromJSON,
    BaseWackerNeusonKramerAdapterFromJSONTyped,
    BaseWackerNeusonKramerAdapterToJSON,
} from './';

/**
 * 
 * @export
 * @interface WackerNeusonKramerAdapter
 */
export interface WackerNeusonKramerAdapter {
    /**
     * 
     * @type {number}
     * @memberof WackerNeusonKramerAdapter
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof WackerNeusonKramerAdapter
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    adapterName: string;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    cronExpression: string;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    dataUrl: string;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    tokenUrl: string;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof WackerNeusonKramerAdapter
     */
    clientSecret: string;
}

export function WackerNeusonKramerAdapterFromJSON(json: any): WackerNeusonKramerAdapter {
    return WackerNeusonKramerAdapterFromJSONTyped(json, false);
}

export function WackerNeusonKramerAdapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): WackerNeusonKramerAdapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'adapterName': json['adapter_name'],
        'cronExpression': json['cron_expression'],
        'dataUrl': json['data_url'],
        'tokenUrl': json['token_url'],
        'username': json['username'],
        'password': json['password'],
        'clientId': json['client_id'],
        'clientSecret': json['client_secret'],
    };
}

export function WackerNeusonKramerAdapterToJSON(value?: WackerNeusonKramerAdapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'user_id': value.userId,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'adapter_name': value.adapterName,
        'cron_expression': value.cronExpression,
        'data_url': value.dataUrl,
        'token_url': value.tokenUrl,
        'username': value.username,
        'password': value.password,
        'client_id': value.clientId,
        'client_secret': value.clientSecret,
    };
}
