version: "3.8"

services:
  fastapi:
    stdin_open: true
    tty: true
    build:
      context: ../fastapi-master-api
      dockerfile: Dockerfile
      target: dev
    expose:
      - 80
    ports:
      - 80:80
      - 4445:4445
    env_file: &envfile
      - ../fastapi-master-api/.env
    volumes:
      - ../fastapi-master-api/app:/usr/src/app/app
      - ../fastapi-master-api/tests:/usr/src/app/tests
      - ../fastapi-master-api/pyproject.toml:/usr/src/app/pyproject.toml
      - ../fastapi-master-api/poetry.lock:/usr/src/app/poetry.lock
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    env_file: *envfile
    ports:
      - "5432:5432"

volumes:
  postgres_data: