version: "3.8"


services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  fastapi:
    stdin_open: true
    tty: true
    build:
      context: ../fastapi-master-api
      dockerfile: Dockerfile
      target: dev
    command: uvicorn app.main:create_app --host 0.0.0.0 --port 80 --reload
    expose:
      - 80
    ports:
      - 80:80
      - 4445:4445
    env_file: &envfile
      - ../fastapi-master-api/.env
    volumes:
      - ../fastapi-master-api/alembic:/usr/src/app/
      - ../fastapi-master-api/app:/usr/src/app/app
      - ../fastapi-master-api/tests:/usr/src/app/tests
      - ../fastapi-master-api/pyproject.toml:/usr/src/app/pyproject.toml
      - ../fastapi-master-api/poetry.lock:/usr/src/app/poetry.lock
      - ../fastapi-master-api/alembic:/usr/src/app/alembic
      - ../fastapi-master-api/alembic.ini:/usr/src/app/alembic.ini
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    env_file: *envfile
    ports:
      - "5432:5432"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgres_data:
