version: "3.8"

services:
  fastapi:
    stdin_open: true
    tty: true
    build:
      context: $PWD/fastapi-master-api
      dockerfile: Dockerfile
      target: dev
    expose:
      - 80
    ports:
      - 80:80
      - 4445:4445
    env_file:
      - $PWD/fastapi-master-api/.env
    secrets:
      - gstorage-service-account.json
    volumes:
      - $PWD/fastapi-master-api/app:/usr/src/app/app
      - $PWD/fastapi-master-api/tests:/usr/src/app/tests
      - $PWD/fastapi-master-api/pyproject.toml:/usr/src/app/pyproject.toml
      - $PWD/fastapi-master-api/poetry.lock:/usr/src/app/poetry.lock

  api-server:
    stdin_open: true
    tty: true
    build:
      context: $PWD/fastapi-master-api
      target: dev
    hostname: ${DJANGO_HOST}
    volumes: &volumes
      - ./:/usr/src/app
    ports:
      - 8000:8000
      - 4444:4444
    env_file: &envfile
      - $PWD/fastapi-master-api/.env
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: *envfile
    ports:
      - 5432:5432

volumes:
  postgres_data: