variables:
  NODE_VERSION: "16.2"
  DOCKER_VERSION: "20.10.8"
  DOCKER_BUILDKIT: 1
  DOCKER_TLS_CERTDIR: /certs
  # Workaround until Gitlab runner fix is available
  FF_NETWORK_PER_BUILD: 1

stages:
  - Test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: docker:${DOCKER_VERSION}-git

services:
  - docker:${DOCKER_VERSION}-dind

#######################################################################################################################
# Test
#######################################################################################################################

lint:
  image: node:${NODE_VERSION}
  stage: Test
  before_script:
    - echo "----------Starting Linting and Formatting Job for OpenAPI Spec----------"
    - cd tacto-api
    - echo "----------Installing Dependencies for Linting and Formatting----------"
    - yarn install --cache-folder .yarn
  script:
    - echo "----------Linting OpenAPI Spec----------"
    - yarn run lint
    - echo "----------Build OpenAPI Spec----------"
    - yarn run build
    - git diff --exit-code
    - echo "----------Validate OpenAPI Spec----------"
    - yarn run test
  interruptible: true

generate-api-spec:
  stage: Test
  variables:
    OPENAPI_GEN_VERSION: "v5.3.0"
    API_SPEC: "/tacto-api/build/openapi.yaml"
  script:
    - rm -rf frontend/src/api
    - docker run --rm
      -v ${PWD}:/local
      openapitools/openapi-generator-cli:${OPENAPI_GEN_VERSION}
      generate
      -i "/local${API_SPEC}"
      -g typescript-fetch
      -t "/local/tacto-api/generator-overrides/typescript" 
      -o /local/frontend/src/api 
      --type-mappings=DateTime=string 
      --additional-properties=withInterfaces=true,typescriptThreePlus=true
    - git diff --exit-code
  interruptible: true
