name: Mercedes Connected Car Adapter CI

on:
  push:
    paths:
    - 'mercedes-connected-car-adapter/**'
  
jobs:

  test:
    name: Black and PyTest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        run: pip install poetry
        working-directory: ./mercedes-connected-car-adapter
        
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./mercedes-connected-car-adapter
        
      - name: Code Quality
        run: poetry run black . --check
        working-directory: ./mercedes-connected-car-adapter
        
      - name: Test with pytest
        run: poetry run pytest --cov .
        working-directory: ./mercedes-connected-car-adapter
